### ISSUE TITLE
Lastest Version is Broken

### ISSUE THREAD

**Issue by Bonboon229** [Plouni/smash_wav_to_pcm#2]
This error pops up in the command line

Traceback (most recent call last):
  File "C:\Users\goji\Downloads\SCM\download_song_from_id_game.py", line 6, in <module>
    import download_from_id_song
  File "C:\Users\goji\Downloads\SCM\download_from_id_song.py", line 26, in <module>
    list_tracks_file = config['list_tracks_file']
KeyError: 'list_tracks_file

**Comment by Plouni** [comment]
I fixed it, there was a missing field in the config file. Grab the latest version and make sure your config file has the field 'list_tracks_file'.
